'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.225
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("_1gDesktop.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _1g1g1() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_1g1g1", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Favorites() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Favorites", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property favorites_tabkber() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("favorites_tabkber", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Favorites1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Favorites1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Gear() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Gear", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Gear1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gear1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Lock() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Lock", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property lock_taskbar() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("lock_taskbar", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Lock1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lock1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Media_Player1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Media_Player1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Mute() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Mute", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Mute1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mute1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property next_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("next_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property next_over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("next_over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property next_up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("next_up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property note_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("note_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property note_over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("note_over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property note_up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("note_up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pause_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pause_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pause_over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pause_over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pause_up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pause_up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Play() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Play", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property play_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("play_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property play_over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("play_over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property play_pause_taskbar() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("play_pause_taskbar", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property play_up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("play_up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Power() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Power", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Power1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Power1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Search() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Search", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Search1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Search1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sound() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Sound", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Sound1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sound1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Twitter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Twitter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Twitter1() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Twitter1", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
